
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: lab-investimento
  datasource:
    url: jdbc:h2:mem:lab_investment;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: password
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true



lab:
  investment:
    paths:
      client-account-name: "account-microservice"
      client-account-base-url: "http://localhost:8081"
      client-account-balance-path-url: "/api/v1/accounts/{accountId}/balance"
      client-account-debit-path-url: "/api/v1/accounts/{accountId}/debit"
    exceptions:
      product-dont-exists-message: "Prouto n�o encontrado."
      product-dont-exists-description: "N�o foi poss�vel encontrar o produto informado."
      account-without-balance-message: "Saldo insuficiente."
      account-without-balance-description: "N�o foi poss�vel efetuar o investimento, o saldo da conta informada � insuficiente."
      account-without-balance-for-product-private-message: "Produto selecionado n�o pode ser Private."
      account-without-balance-for-product-private-description: "O produto selecionado � da modalidade Private, por�m seus recursos n�o s�o compat�veis para esse investimento."
      account-is-not-debited-message: "N�o foi poss�vel debitar da sua conta corrente."
      account-is-not-debited-description: "N�o foi poss�vel efetuar o d�bito e confirmar seu investimento, tivemos um problema em nossos servi�os."